### ISSUE TITLE
使用自定义tabbar切换页面闪屏如何解决

### ISSUE THREAD

**Issue by aahowe** [LonJinUp/wxTabBar#1]
由于自定义tabbar每个页面都是单独的实例，在页面切换以后会导致动画衔接不同步，如何解决这一问题

**Comment by LonJinUp** [comment]
你是说tabbar的动画吗？

**Comment by aahowe** [comment]
是的，我把这个demo放到了小程序官方的自定义tabbar，因为官方的实现在切换页面的时候同时会切换tabbar实例，所以动画会衔接不上，是不是只能在同一个页面中放这个动画tabbar

**Comment by LonJinUp** [comment]
最好的解决方案就是我这种，tabbar在一个页面，然后tab页面通过组件方式引入

**Comment by aahowe** [comment]
感谢
